import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Hero from '../components/Hero'
import About from '../components/About'
import Experience from '../components/Experience'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Contact from '../components/Contact'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#f7ab0a]/80">
      <Head>
        <title>Splax's Portfolio</title>
        <meta name="description" content="Generated by splax" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <section id="hero" className="snap-start">
      <Hero/>
      </section>

      <section id="about" className="snap-center">
        <About/>
      </section>

      <section id="experience" className="snap-center">
        <Experience/>
      </section>

      <section id="skills" className="snap-start">
        <Skills/>
      </section>

      <section id="projects" className="snap-start">
        <Projects/>
      </section>

      <section id="contact" className="snap-start">
        <Contact/>
      </section>

      <Link href="#hero">
        <footer className='sticky bottom-5 w-full cursor-pointer'>
          <div className="flex items-center justify-center">
            <img
            className='h-10 w-10 rounded-full filter grayscale hover:grayscale-0'
            alt="" src="https://media.licdn.com/dms/image/D4D03AQH7H3eewkf2ew/profile-displayphoto-shrink_800_800/0/1669147728701?e=1678320000&v=beta&t=vGo_bIjOhEFTHeDncYwihvjmAu7xaG5xcgJ9TY4LYAs"/>
          </div>
        </footer>
      </Link>
    </div>
  )
}
